<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('permissions')->delete();
        
        \DB::table('permissions')->insert(array (
            0 => 
            array (
                'created_at' => '2023-03-19 16:25:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 1,
                'name' => 'Dashboard',
                'parent' => 'Dashboard',
                'status' => 1,
                'updated_at' => '2023-03-19 16:25:23',
            ),
            1 => 
            array (
                'created_at' => '2023-03-19 18:08:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 2,
                'name' => 'User List',
                'parent' => 'User',
                'status' => 1,
                'updated_at' => '2023-03-19 18:08:09',
            ),
            2 => 
            array (
                'created_at' => '2023-03-19 18:08:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 3,
                'name' => 'User Create',
                'parent' => 'User',
                'status' => 1,
                'updated_at' => '2023-03-19 18:08:09',
            ),
            3 => 
            array (
                'created_at' => '2023-03-19 18:08:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 4,
                'name' => 'User Edit',
                'parent' => 'User',
                'status' => 1,
                'updated_at' => '2023-03-19 18:08:09',
            ),
            4 => 
            array (
                'created_at' => '2023-03-19 18:08:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 5,
                'name' => 'User Delete',
                'parent' => 'User',
                'status' => 1,
                'updated_at' => '2023-03-19 18:08:09',
            ),
            5 => 
            array (
                'created_at' => '2023-03-19 18:08:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 6,
                'name' => 'User View',
                'parent' => 'User',
                'status' => 1,
                'updated_at' => '2023-03-19 18:08:09',
            ),
            6 => 
            array (
                'created_at' => '2023-03-19 18:08:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 7,
                'name' => 'User Print',
                'parent' => 'User',
                'status' => 1,
                'updated_at' => '2023-03-19 18:08:09',
            ),
            7 => 
            array (
                'created_at' => '2023-03-19 18:08:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 8,
                'name' => 'User Restore',
                'parent' => 'User',
                'status' => 1,
                'updated_at' => '2023-03-19 18:08:09',
            ),
            8 => 
            array (
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 9,
                'name' => 'Role List',
                'parent' => 'Role',
                'status' => 1,
                'updated_at' => '2023-03-19 18:17:22',
            ),
            9 => 
            array (
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 10,
                'name' => 'Role Create',
                'parent' => 'Role',
                'status' => 1,
                'updated_at' => '2023-03-19 18:17:22',
            ),
            10 => 
            array (
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 11,
                'name' => 'Role Edit',
                'parent' => 'Role',
                'status' => 1,
                'updated_at' => '2023-03-19 18:17:22',
            ),
            11 => 
            array (
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 12,
                'name' => 'Role Delete',
                'parent' => 'Role',
                'status' => 1,
                'updated_at' => '2023-03-19 18:17:22',
            ),
            12 => 
            array (
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 13,
                'name' => 'Role View',
                'parent' => 'Role',
                'status' => 1,
                'updated_at' => '2023-03-19 18:17:22',
            ),
            13 => 
            array (
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 14,
                'name' => 'Role Print',
                'parent' => 'Role',
                'status' => 1,
                'updated_at' => '2023-03-19 18:17:22',
            ),
            14 => 
            array (
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 15,
                'name' => 'Role Restore',
                'parent' => 'Role',
                'status' => 1,
                'updated_at' => '2023-03-19 18:17:22',
            ),
            15 => 
            array (
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 16,
                'name' => 'Role Permission',
                'parent' => 'Role',
                'status' => 1,
                'updated_at' => '2023-03-19 18:17:22',
            ),
            16 => 
            array (
                'created_at' => '2023-03-29 04:28:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 18,
                'name' => 'Apps Information List',
                'parent' => 'Apps Information',
                'status' => 1,
                'updated_at' => '2023-03-29 04:28:32',
            ),
            17 => 
            array (
                'created_at' => '2023-03-29 04:28:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 19,
                'name' => 'Apps Information Create',
                'parent' => 'Apps Information',
                'status' => 1,
                'updated_at' => '2023-03-29 04:28:32',
            ),
            18 => 
            array (
                'created_at' => '2023-03-29 04:28:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 20,
                'name' => 'Apps Information Edit',
                'parent' => 'Apps Information',
                'status' => 1,
                'updated_at' => '2023-03-29 04:28:32',
            ),
            19 => 
            array (
                'created_at' => '2023-03-29 04:28:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 21,
                'name' => 'Apps Information Delete',
                'parent' => 'Apps Information',
                'status' => 1,
                'updated_at' => '2023-03-29 04:28:32',
            ),
            20 => 
            array (
                'created_at' => '2023-03-29 04:28:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 22,
                'name' => 'Apps Information View',
                'parent' => 'Apps Information',
                'status' => 1,
                'updated_at' => '2023-03-29 04:28:32',
            ),
            21 => 
            array (
                'created_at' => '2023-03-29 04:28:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 23,
                'name' => 'Apps Information Print',
                'parent' => 'Apps Information',
                'status' => 1,
                'updated_at' => '2023-03-29 04:28:32',
            ),
            22 => 
            array (
                'created_at' => '2023-03-29 04:28:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 24,
                'name' => 'Apps Information Edit_history',
                'parent' => 'Apps Information',
                'status' => 1,
                'updated_at' => '2023-03-29 04:28:32',
            ),
            23 => 
            array (
                'created_at' => '2023-03-29 04:35:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 27,
                'name' => 'About Us Create',
                'parent' => 'About Us',
                'status' => 1,
                'updated_at' => '2023-03-29 04:35:23',
            ),
            24 => 
            array (
                'created_at' => '2023-03-29 04:35:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 28,
                'name' => 'About Us Edit',
                'parent' => 'About Us',
                'status' => 1,
                'updated_at' => '2023-03-29 04:35:23',
            ),
            25 => 
            array (
                'created_at' => '2023-03-29 04:35:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 29,
                'name' => 'About Us Delete',
                'parent' => 'About Us',
                'status' => 1,
                'updated_at' => '2023-03-29 04:35:23',
            ),
            26 => 
            array (
                'created_at' => '2023-03-29 04:35:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 30,
                'name' => 'About Us View',
                'parent' => 'About Us',
                'status' => 1,
                'updated_at' => '2023-03-29 04:35:23',
            ),
            27 => 
            array (
                'created_at' => '2023-03-29 04:35:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 31,
                'name' => 'About Us Print',
                'parent' => 'About Us',
                'status' => 1,
                'updated_at' => '2023-03-29 04:35:23',
            ),
            28 => 
            array (
                'created_at' => '2023-03-29 04:35:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 32,
                'name' => 'About Us Edit_history',
                'parent' => 'About Us',
                'status' => 1,
                'updated_at' => '2023-03-29 04:35:23',
            ),
            29 => 
            array (
                'created_at' => '2023-03-29 09:02:52',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 41,
                'name' => 'Website Info Edit_history',
                'parent' => 'Website Info',
                'status' => 1,
                'updated_at' => '2023-03-29 09:02:52',
            ),
            30 => 
            array (
                'created_at' => '2023-03-30 05:45:25',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 49,
                'name' => 'Photo Gallery Edit_history',
                'parent' => 'Photo Gallery',
                'status' => 1,
                'updated_at' => '2023-03-30 05:45:25',
            ),
            31 => 
            array (
                'created_at' => '2023-04-01 06:32:18',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 56,
                'name' => 'Services Edit_history',
                'parent' => 'Services',
                'status' => 1,
                'updated_at' => '2023-04-01 06:32:18',
            ),
            32 => 
            array (
                'created_at' => '2023-04-01 08:52:40',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 64,
                'name' => 'Project Info List',
                'parent' => 'Project Info',
                'status' => 1,
                'updated_at' => '2023-04-01 08:52:40',
            ),
            33 => 
            array (
                'created_at' => '2023-04-01 08:52:40',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 65,
                'name' => 'Project Info Create',
                'parent' => 'Project Info',
                'status' => 1,
                'updated_at' => '2023-04-01 08:52:40',
            ),
            34 => 
            array (
                'created_at' => '2023-04-01 08:52:40',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 66,
                'name' => 'Project Info Edit',
                'parent' => 'Project Info',
                'status' => 1,
                'updated_at' => '2023-04-01 08:52:40',
            ),
            35 => 
            array (
                'created_at' => '2023-04-01 08:52:40',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 67,
                'name' => 'Project Info Delete',
                'parent' => 'Project Info',
                'status' => 1,
                'updated_at' => '2023-04-01 08:52:40',
            ),
            36 => 
            array (
                'created_at' => '2023-04-01 08:52:40',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 68,
                'name' => 'Project Info View',
                'parent' => 'Project Info',
                'status' => 1,
                'updated_at' => '2023-04-01 08:52:40',
            ),
            37 => 
            array (
                'created_at' => '2023-04-01 08:52:40',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 69,
                'name' => 'Project Info Print',
                'parent' => 'Project Info',
                'status' => 1,
                'updated_at' => '2023-04-01 08:52:40',
            ),
            38 => 
            array (
                'created_at' => '2023-04-01 08:52:40',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 70,
                'name' => 'Project Info Edit_history',
                'parent' => 'Project Info',
                'status' => 1,
                'updated_at' => '2023-04-01 08:52:40',
            ),
            39 => 
            array (
                'created_at' => '2023-04-01 08:53:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 71,
                'name' => 'Project Category List',
                'parent' => 'Project Category',
                'status' => 1,
                'updated_at' => '2023-04-01 08:53:23',
            ),
            40 => 
            array (
                'created_at' => '2023-04-01 08:53:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 72,
                'name' => 'Project Category Create',
                'parent' => 'Project Category',
                'status' => 1,
                'updated_at' => '2023-04-01 08:53:23',
            ),
            41 => 
            array (
                'created_at' => '2023-04-01 08:53:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 73,
                'name' => 'Project Category Edit',
                'parent' => 'Project Category',
                'status' => 1,
                'updated_at' => '2023-04-01 08:53:23',
            ),
            42 => 
            array (
                'created_at' => '2023-04-01 08:53:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 74,
                'name' => 'Project Category Delete',
                'parent' => 'Project Category',
                'status' => 1,
                'updated_at' => '2023-04-01 08:53:23',
            ),
            43 => 
            array (
                'created_at' => '2023-04-01 08:53:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 75,
                'name' => 'Project Category View',
                'parent' => 'Project Category',
                'status' => 1,
                'updated_at' => '2023-04-01 08:53:23',
            ),
            44 => 
            array (
                'created_at' => '2023-04-01 08:53:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 76,
                'name' => 'Project Category Print',
                'parent' => 'Project Category',
                'status' => 1,
                'updated_at' => '2023-04-01 08:53:23',
            ),
            45 => 
            array (
                'created_at' => '2023-04-01 08:53:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 77,
                'name' => 'Project Category Edit_history',
                'parent' => 'Project Category',
                'status' => 1,
                'updated_at' => '2023-04-01 08:53:23',
            ),
            46 => 
            array (
                'created_at' => '2023-04-01 10:15:03',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 91,
                'name' => 'Project Information Edit_history',
                'parent' => 'Project Information',
                'status' => 1,
                'updated_at' => '2023-04-01 10:15:03',
            ),
            47 => 
            array (
                'created_at' => '2023-04-02 05:48:12',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 98,
                'name' => 'Testimonial Edit_history',
                'parent' => 'Testimonial',
                'status' => 1,
                'updated_at' => '2023-04-02 05:48:12',
            ),
            48 => 
            array (
                'created_at' => '2023-04-03 06:46:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 113,
                'name' => 'Our Team Edit_history',
                'parent' => 'Our Team',
                'status' => 1,
                'updated_at' => '2023-04-03 06:46:32',
            ),
            49 => 
            array (
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 114,
                'name' => 'Menu List',
                'parent' => 'Menu',
                'status' => 1,
                'updated_at' => '2023-04-03 10:39:32',
            ),
            50 => 
            array (
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 115,
                'name' => 'Menu Create',
                'parent' => 'Menu',
                'status' => 1,
                'updated_at' => '2023-04-03 10:39:32',
            ),
            51 => 
            array (
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 116,
                'name' => 'Menu Edit',
                'parent' => 'Menu',
                'status' => 1,
                'updated_at' => '2023-04-03 10:39:32',
            ),
            52 => 
            array (
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 117,
                'name' => 'Menu Delete',
                'parent' => 'Menu',
                'status' => 1,
                'updated_at' => '2023-04-03 10:39:32',
            ),
            53 => 
            array (
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 118,
                'name' => 'Menu View',
                'parent' => 'Menu',
                'status' => 1,
                'updated_at' => '2023-04-03 10:39:32',
            ),
            54 => 
            array (
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 119,
                'name' => 'Menu Deleted_list',
                'parent' => 'Menu',
                'status' => 1,
                'updated_at' => '2023-04-03 10:39:32',
            ),
            55 => 
            array (
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 120,
                'name' => 'Menu Restore',
                'parent' => 'Menu',
                'status' => 1,
                'updated_at' => '2023-04-03 10:39:32',
            ),
            56 => 
            array (
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 121,
                'name' => 'Menu Permanent_delete',
                'parent' => 'Menu',
                'status' => 1,
                'updated_at' => '2023-04-03 10:39:32',
            ),
            57 => 
            array (
                'created_at' => '2023-04-05 07:01:18',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 128,
                'name' => 'Member Edit_history',
                'parent' => 'Member',
                'status' => 1,
                'updated_at' => '2023-04-05 07:01:18',
            ),
            58 => 
            array (
                'created_at' => '2023-04-05 07:01:18',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 129,
                'name' => 'Member Deleted_list',
                'parent' => 'Member',
                'status' => 1,
                'updated_at' => '2023-04-05 07:01:18',
            ),
            59 => 
            array (
                'created_at' => '2023-04-05 07:01:18',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 131,
                'name' => 'Member Permanent_delete',
                'parent' => 'Member',
                'status' => 1,
                'updated_at' => '2023-04-05 07:01:18',
            ),
            60 => 
            array (
                'created_at' => '2023-04-19 07:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 132,
                'name' => 'Company Information List',
                'parent' => 'Company Information',
                'status' => 1,
                'updated_at' => '2023-04-19 07:39:32',
            ),
            61 => 
            array (
                'created_at' => '2023-04-19 07:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 133,
                'name' => 'Company Information Create',
                'parent' => 'Company Information',
                'status' => 1,
                'updated_at' => '2023-04-19 07:39:32',
            ),
            62 => 
            array (
                'created_at' => '2023-04-19 07:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 134,
                'name' => 'Company Information Edit',
                'parent' => 'Company Information',
                'status' => 1,
                'updated_at' => '2023-04-19 07:39:32',
            ),
            63 => 
            array (
                'created_at' => '2023-04-19 07:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 135,
                'name' => 'Company Information Delete',
                'parent' => 'Company Information',
                'status' => 1,
                'updated_at' => '2023-04-19 07:39:32',
            ),
            64 => 
            array (
                'created_at' => '2023-04-19 07:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 136,
                'name' => 'Company Information View',
                'parent' => 'Company Information',
                'status' => 1,
                'updated_at' => '2023-04-19 07:39:32',
            ),
            65 => 
            array (
                'created_at' => '2023-04-19 07:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 137,
                'name' => 'Company Information Print',
                'parent' => 'Company Information',
                'status' => 1,
                'updated_at' => '2023-04-19 07:39:32',
            ),
            66 => 
            array (
                'created_at' => '2023-04-19 07:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 138,
                'name' => 'Company Information Edit_history',
                'parent' => 'Company Information',
                'status' => 1,
                'updated_at' => '2023-04-19 07:39:32',
            ),
            67 => 
            array (
                'created_at' => '2023-04-19 07:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 139,
                'name' => 'Company Information Deleted_list',
                'parent' => 'Company Information',
                'status' => 1,
                'updated_at' => '2023-04-19 07:39:32',
            ),
            68 => 
            array (
                'created_at' => '2023-04-19 07:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 140,
                'name' => 'Company Information Restore',
                'parent' => 'Company Information',
                'status' => 1,
                'updated_at' => '2023-04-19 07:39:32',
            ),
            69 => 
            array (
                'created_at' => '2023-04-19 07:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 141,
                'name' => 'Company Information Permanent_delete',
                'parent' => 'Company Information',
                'status' => 1,
                'updated_at' => '2023-04-19 07:39:32',
            ),
            70 => 
            array (
                'created_at' => '2023-04-19 07:41:20',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 142,
                'name' => 'Create Customer List',
                'parent' => 'Create Customer',
                'status' => 1,
                'updated_at' => '2023-04-19 07:41:20',
            ),
            71 => 
            array (
                'created_at' => '2023-04-19 07:41:20',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 143,
                'name' => 'Create Customer Create',
                'parent' => 'Create Customer',
                'status' => 1,
                'updated_at' => '2023-04-19 07:41:20',
            ),
            72 => 
            array (
                'created_at' => '2023-04-19 07:41:20',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 144,
                'name' => 'Create Customer Edit',
                'parent' => 'Create Customer',
                'status' => 1,
                'updated_at' => '2023-04-19 07:41:20',
            ),
            73 => 
            array (
                'created_at' => '2023-04-19 07:41:20',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 145,
                'name' => 'Create Customer Delete',
                'parent' => 'Create Customer',
                'status' => 1,
                'updated_at' => '2023-04-19 07:41:20',
            ),
            74 => 
            array (
                'created_at' => '2023-04-19 07:41:20',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 146,
                'name' => 'Create Customer View',
                'parent' => 'Create Customer',
                'status' => 1,
                'updated_at' => '2023-04-19 07:41:20',
            ),
            75 => 
            array (
                'created_at' => '2023-04-19 07:41:20',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 147,
                'name' => 'Create Customer Print',
                'parent' => 'Create Customer',
                'status' => 1,
                'updated_at' => '2023-04-19 07:41:20',
            ),
            76 => 
            array (
                'created_at' => '2023-04-19 07:41:20',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 148,
                'name' => 'Create Customer Edit_history',
                'parent' => 'Create Customer',
                'status' => 1,
                'updated_at' => '2023-04-19 07:41:20',
            ),
            77 => 
            array (
                'created_at' => '2023-04-19 07:41:20',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 149,
                'name' => 'Create Customer Deleted_list',
                'parent' => 'Create Customer',
                'status' => 1,
                'updated_at' => '2023-04-19 07:41:20',
            ),
            78 => 
            array (
                'created_at' => '2023-04-19 07:41:20',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 150,
                'name' => 'Create Customer Restore',
                'parent' => 'Create Customer',
                'status' => 1,
                'updated_at' => '2023-04-19 07:41:20',
            ),
            79 => 
            array (
                'created_at' => '2023-04-19 07:41:20',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 151,
                'name' => 'Create Customer Permanent_delete',
                'parent' => 'Create Customer',
                'status' => 1,
                'updated_at' => '2023-04-19 07:41:20',
            ),
            80 => 
            array (
                'created_at' => '2023-04-29 06:36:51',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 152,
                'name' => 'Manage Customer List',
                'parent' => 'Manage Customer',
                'status' => 1,
                'updated_at' => '2023-04-29 06:36:51',
            ),
            81 => 
            array (
                'created_at' => '2023-04-29 06:36:51',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 153,
                'name' => 'Manage Customer Create',
                'parent' => 'Manage Customer',
                'status' => 1,
                'updated_at' => '2023-04-29 06:36:51',
            ),
            82 => 
            array (
                'created_at' => '2023-04-29 06:36:51',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 154,
                'name' => 'Manage Customer Edit',
                'parent' => 'Manage Customer',
                'status' => 1,
                'updated_at' => '2023-04-29 06:36:51',
            ),
            83 => 
            array (
                'created_at' => '2023-04-29 06:36:51',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 155,
                'name' => 'Manage Customer Delete',
                'parent' => 'Manage Customer',
                'status' => 1,
                'updated_at' => '2023-04-29 06:36:51',
            ),
            84 => 
            array (
                'created_at' => '2023-04-29 06:36:51',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 156,
                'name' => 'Manage Customer View',
                'parent' => 'Manage Customer',
                'status' => 1,
                'updated_at' => '2023-04-29 06:36:51',
            ),
            85 => 
            array (
                'created_at' => '2023-04-29 06:36:51',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 157,
                'name' => 'Manage Customer Print',
                'parent' => 'Manage Customer',
                'status' => 1,
                'updated_at' => '2023-04-29 06:36:51',
            ),
            86 => 
            array (
                'created_at' => '2023-04-29 06:36:51',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 158,
                'name' => 'Manage Customer Edit_history',
                'parent' => 'Manage Customer',
                'status' => 1,
                'updated_at' => '2023-04-29 06:36:51',
            ),
            87 => 
            array (
                'created_at' => '2023-04-29 06:36:51',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 159,
                'name' => 'Manage Customer Deleted_list',
                'parent' => 'Manage Customer',
                'status' => 1,
                'updated_at' => '2023-04-29 06:36:51',
            ),
            88 => 
            array (
                'created_at' => '2023-04-29 06:36:51',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 160,
                'name' => 'Manage Customer Restore',
                'parent' => 'Manage Customer',
                'status' => 1,
                'updated_at' => '2023-04-29 06:36:51',
            ),
            89 => 
            array (
                'created_at' => '2023-04-29 06:36:51',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 161,
                'name' => 'Manage Customer Permanent_delete',
                'parent' => 'Manage Customer',
                'status' => 1,
                'updated_at' => '2023-04-29 06:36:51',
            ),
            90 => 
            array (
                'created_at' => '2023-04-29 09:45:16',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 162,
                'name' => 'Create Supplier List',
                'parent' => 'Create Supplier',
                'status' => 1,
                'updated_at' => '2023-04-29 09:45:16',
            ),
            91 => 
            array (
                'created_at' => '2023-04-29 09:45:16',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 163,
                'name' => 'Create Supplier Create',
                'parent' => 'Create Supplier',
                'status' => 1,
                'updated_at' => '2023-04-29 09:45:16',
            ),
            92 => 
            array (
                'created_at' => '2023-04-29 09:45:16',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 164,
                'name' => 'Create Supplier Edit',
                'parent' => 'Create Supplier',
                'status' => 1,
                'updated_at' => '2023-04-29 09:45:16',
            ),
            93 => 
            array (
                'created_at' => '2023-04-29 09:45:16',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 165,
                'name' => 'Create Supplier Delete',
                'parent' => 'Create Supplier',
                'status' => 1,
                'updated_at' => '2023-04-29 09:45:16',
            ),
            94 => 
            array (
                'created_at' => '2023-04-29 09:45:16',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 166,
                'name' => 'Create Supplier View',
                'parent' => 'Create Supplier',
                'status' => 1,
                'updated_at' => '2023-04-29 09:45:16',
            ),
            95 => 
            array (
                'created_at' => '2023-04-29 09:45:16',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 167,
                'name' => 'Create Supplier Print',
                'parent' => 'Create Supplier',
                'status' => 1,
                'updated_at' => '2023-04-29 09:45:16',
            ),
            96 => 
            array (
                'created_at' => '2023-04-29 09:45:16',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 168,
                'name' => 'Create Supplier Edit_history',
                'parent' => 'Create Supplier',
                'status' => 1,
                'updated_at' => '2023-04-29 09:45:16',
            ),
            97 => 
            array (
                'created_at' => '2023-04-29 09:45:16',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 169,
                'name' => 'Create Supplier Deleted_list',
                'parent' => 'Create Supplier',
                'status' => 1,
                'updated_at' => '2023-04-29 09:45:16',
            ),
            98 => 
            array (
                'created_at' => '2023-04-29 09:45:16',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 170,
                'name' => 'Create Supplier Restore',
                'parent' => 'Create Supplier',
                'status' => 1,
                'updated_at' => '2023-04-29 09:45:16',
            ),
            99 => 
            array (
                'created_at' => '2023-04-29 09:45:16',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 171,
                'name' => 'Create Supplier Permanent_delete',
                'parent' => 'Create Supplier',
                'status' => 1,
                'updated_at' => '2023-04-29 09:45:16',
            ),
            100 => 
            array (
                'created_at' => '2023-04-29 10:30:41',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 172,
                'name' => 'Manage Supplier List',
                'parent' => 'Manage Supplier',
                'status' => 1,
                'updated_at' => '2023-04-29 10:30:41',
            ),
            101 => 
            array (
                'created_at' => '2023-04-29 10:30:41',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 173,
                'name' => 'Manage Supplier Edit',
                'parent' => 'Manage Supplier',
                'status' => 1,
                'updated_at' => '2023-04-29 10:30:41',
            ),
            102 => 
            array (
                'created_at' => '2023-04-29 10:30:41',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 174,
                'name' => 'Manage Supplier Delete',
                'parent' => 'Manage Supplier',
                'status' => 1,
                'updated_at' => '2023-04-29 10:30:41',
            ),
            103 => 
            array (
                'created_at' => '2023-04-29 10:30:41',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 175,
                'name' => 'Manage Supplier View',
                'parent' => 'Manage Supplier',
                'status' => 1,
                'updated_at' => '2023-04-29 10:30:41',
            ),
            104 => 
            array (
                'created_at' => '2023-04-29 10:30:41',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 176,
                'name' => 'Manage Supplier Edit_history',
                'parent' => 'Manage Supplier',
                'status' => 1,
                'updated_at' => '2023-04-29 10:30:41',
            ),
            105 => 
            array (
                'created_at' => '2023-04-29 10:30:41',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 177,
                'name' => 'Manage Supplier Deleted_list',
                'parent' => 'Manage Supplier',
                'status' => 1,
                'updated_at' => '2023-04-29 10:30:41',
            ),
            106 => 
            array (
                'created_at' => '2023-04-29 10:30:41',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 178,
                'name' => 'Manage Supplier Restore',
                'parent' => 'Manage Supplier',
                'status' => 1,
                'updated_at' => '2023-04-29 10:30:41',
            ),
            107 => 
            array (
                'created_at' => '2023-04-29 10:30:41',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 179,
                'name' => 'Manage Supplier Permanent_delete',
                'parent' => 'Manage Supplier',
                'status' => 1,
                'updated_at' => '2023-04-29 10:30:41',
            ),
            108 => 
            array (
                'created_at' => '2023-04-30 04:37:07',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 180,
                'name' => 'Item List',
                'parent' => 'Item',
                'status' => 1,
                'updated_at' => '2023-04-30 04:37:07',
            ),
            109 => 
            array (
                'created_at' => '2023-04-30 04:37:07',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 181,
                'name' => 'Item Create',
                'parent' => 'Item',
                'status' => 1,
                'updated_at' => '2023-04-30 04:37:07',
            ),
            110 => 
            array (
                'created_at' => '2023-04-30 04:37:07',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 182,
                'name' => 'Item Edit',
                'parent' => 'Item',
                'status' => 1,
                'updated_at' => '2023-04-30 04:37:07',
            ),
            111 => 
            array (
                'created_at' => '2023-04-30 04:37:07',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 183,
                'name' => 'Item Delete',
                'parent' => 'Item',
                'status' => 1,
                'updated_at' => '2023-04-30 04:37:07',
            ),
            112 => 
            array (
                'created_at' => '2023-04-30 04:37:07',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 184,
                'name' => 'Item View',
                'parent' => 'Item',
                'status' => 1,
                'updated_at' => '2023-04-30 04:37:07',
            ),
            113 => 
            array (
                'created_at' => '2023-04-30 04:37:07',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 185,
                'name' => 'Item Print',
                'parent' => 'Item',
                'status' => 1,
                'updated_at' => '2023-04-30 04:37:07',
            ),
            114 => 
            array (
                'created_at' => '2023-04-30 04:37:07',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 186,
                'name' => 'Item Edit_history',
                'parent' => 'Item',
                'status' => 1,
                'updated_at' => '2023-04-30 04:37:07',
            ),
            115 => 
            array (
                'created_at' => '2023-04-30 04:37:07',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 187,
                'name' => 'Item Deleted_list',
                'parent' => 'Item',
                'status' => 1,
                'updated_at' => '2023-04-30 04:37:07',
            ),
            116 => 
            array (
                'created_at' => '2023-04-30 04:37:07',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 188,
                'name' => 'Item Restore',
                'parent' => 'Item',
                'status' => 1,
                'updated_at' => '2023-04-30 04:37:07',
            ),
            117 => 
            array (
                'created_at' => '2023-04-30 04:37:08',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 189,
                'name' => 'Item Permanent_delete',
                'parent' => 'Item',
                'status' => 1,
                'updated_at' => '2023-04-30 04:37:08',
            ),
            118 => 
            array (
                'created_at' => '2023-04-30 05:49:04',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 190,
                'name' => 'Category List',
                'parent' => 'Category',
                'status' => 1,
                'updated_at' => '2023-04-30 05:49:04',
            ),
            119 => 
            array (
                'created_at' => '2023-04-30 05:49:04',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 191,
                'name' => 'Category Create',
                'parent' => 'Category',
                'status' => 1,
                'updated_at' => '2023-04-30 05:49:04',
            ),
            120 => 
            array (
                'created_at' => '2023-04-30 05:49:04',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 192,
                'name' => 'Category Edit',
                'parent' => 'Category',
                'status' => 1,
                'updated_at' => '2023-04-30 05:49:04',
            ),
            121 => 
            array (
                'created_at' => '2023-04-30 05:49:04',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 193,
                'name' => 'Category Delete',
                'parent' => 'Category',
                'status' => 1,
                'updated_at' => '2023-04-30 05:49:04',
            ),
            122 => 
            array (
                'created_at' => '2023-04-30 05:49:04',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 194,
                'name' => 'Category View',
                'parent' => 'Category',
                'status' => 1,
                'updated_at' => '2023-04-30 05:49:04',
            ),
            123 => 
            array (
                'created_at' => '2023-04-30 05:49:04',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 195,
                'name' => 'Category Print',
                'parent' => 'Category',
                'status' => 1,
                'updated_at' => '2023-04-30 05:49:04',
            ),
            124 => 
            array (
                'created_at' => '2023-04-30 05:49:04',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 196,
                'name' => 'Category Edit_history',
                'parent' => 'Category',
                'status' => 1,
                'updated_at' => '2023-04-30 05:49:04',
            ),
            125 => 
            array (
                'created_at' => '2023-04-30 05:49:04',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 197,
                'name' => 'Category Deleted_list',
                'parent' => 'Category',
                'status' => 1,
                'updated_at' => '2023-04-30 05:49:04',
            ),
            126 => 
            array (
                'created_at' => '2023-04-30 05:49:04',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 198,
                'name' => 'Category Restore',
                'parent' => 'Category',
                'status' => 1,
                'updated_at' => '2023-04-30 05:49:04',
            ),
            127 => 
            array (
                'created_at' => '2023-04-30 05:49:04',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 199,
                'name' => 'Category Permanent_delete',
                'parent' => 'Category',
                'status' => 1,
                'updated_at' => '2023-04-30 05:49:04',
            ),
            128 => 
            array (
                'created_at' => '2023-05-01 04:58:07',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 200,
                'name' => 'Brand List',
                'parent' => 'Brand',
                'status' => 1,
                'updated_at' => '2023-05-01 04:58:07',
            ),
            129 => 
            array (
                'created_at' => '2023-05-01 04:58:07',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 201,
                'name' => 'Brand Create',
                'parent' => 'Brand',
                'status' => 1,
                'updated_at' => '2023-05-01 04:58:07',
            ),
            130 => 
            array (
                'created_at' => '2023-05-01 04:58:07',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 202,
                'name' => 'Brand Edit',
                'parent' => 'Brand',
                'status' => 1,
                'updated_at' => '2023-05-01 04:58:07',
            ),
            131 => 
            array (
                'created_at' => '2023-05-01 04:58:07',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 203,
                'name' => 'Brand Delete',
                'parent' => 'Brand',
                'status' => 1,
                'updated_at' => '2023-05-01 04:58:07',
            ),
            132 => 
            array (
                'created_at' => '2023-05-01 04:58:07',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 204,
                'name' => 'Brand View',
                'parent' => 'Brand',
                'status' => 1,
                'updated_at' => '2023-05-01 04:58:07',
            ),
            133 => 
            array (
                'created_at' => '2023-05-01 04:58:07',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 205,
                'name' => 'Brand Print',
                'parent' => 'Brand',
                'status' => 1,
                'updated_at' => '2023-05-01 04:58:07',
            ),
            134 => 
            array (
                'created_at' => '2023-05-01 04:58:07',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 206,
                'name' => 'Brand Edit_history',
                'parent' => 'Brand',
                'status' => 1,
                'updated_at' => '2023-05-01 04:58:07',
            ),
            135 => 
            array (
                'created_at' => '2023-05-01 04:58:07',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 207,
                'name' => 'Brand Deleted_list',
                'parent' => 'Brand',
                'status' => 1,
                'updated_at' => '2023-05-01 04:58:07',
            ),
            136 => 
            array (
                'created_at' => '2023-05-01 04:58:07',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 208,
                'name' => 'Brand Restore',
                'parent' => 'Brand',
                'status' => 1,
                'updated_at' => '2023-05-01 04:58:07',
            ),
            137 => 
            array (
                'created_at' => '2023-05-01 04:58:07',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 209,
                'name' => 'Brand Permanent_delete',
                'parent' => 'Brand',
                'status' => 1,
                'updated_at' => '2023-05-01 04:58:07',
            ),
            138 => 
            array (
                'created_at' => '2023-05-01 05:47:47',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 210,
                'name' => 'Add Product List',
                'parent' => 'Add Product',
                'status' => 1,
                'updated_at' => '2023-05-01 05:47:47',
            ),
            139 => 
            array (
                'created_at' => '2023-05-01 05:47:47',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 211,
                'name' => 'Add Product Create',
                'parent' => 'Add Product',
                'status' => 1,
                'updated_at' => '2023-05-01 05:47:47',
            ),
            140 => 
            array (
                'created_at' => '2023-05-01 05:57:43',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 212,
                'name' => 'Measurement List',
                'parent' => 'Measurement',
                'status' => 1,
                'updated_at' => '2023-05-01 05:57:43',
            ),
            141 => 
            array (
                'created_at' => '2023-05-01 05:57:43',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 213,
                'name' => 'Measurement Create',
                'parent' => 'Measurement',
                'status' => 1,
                'updated_at' => '2023-05-01 05:57:43',
            ),
            142 => 
            array (
                'created_at' => '2023-05-01 05:57:43',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 214,
                'name' => 'Measurement Edit',
                'parent' => 'Measurement',
                'status' => 1,
                'updated_at' => '2023-05-01 05:57:43',
            ),
            143 => 
            array (
                'created_at' => '2023-05-01 05:57:43',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 215,
                'name' => 'Measurement Delete',
                'parent' => 'Measurement',
                'status' => 1,
                'updated_at' => '2023-05-01 05:57:43',
            ),
            144 => 
            array (
                'created_at' => '2023-05-01 05:57:43',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 216,
                'name' => 'Measurement View',
                'parent' => 'Measurement',
                'status' => 1,
                'updated_at' => '2023-05-01 05:57:43',
            ),
            145 => 
            array (
                'created_at' => '2023-05-01 05:57:43',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 217,
                'name' => 'Measurement Print',
                'parent' => 'Measurement',
                'status' => 1,
                'updated_at' => '2023-05-01 05:57:43',
            ),
            146 => 
            array (
                'created_at' => '2023-05-01 05:57:43',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 218,
                'name' => 'Measurement Edit_history',
                'parent' => 'Measurement',
                'status' => 1,
                'updated_at' => '2023-05-01 05:57:43',
            ),
            147 => 
            array (
                'created_at' => '2023-05-01 05:57:43',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 219,
                'name' => 'Measurement Deleted_list',
                'parent' => 'Measurement',
                'status' => 1,
                'updated_at' => '2023-05-01 05:57:43',
            ),
            148 => 
            array (
                'created_at' => '2023-05-01 05:57:43',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 220,
                'name' => 'Measurement Restore',
                'parent' => 'Measurement',
                'status' => 1,
                'updated_at' => '2023-05-01 05:57:43',
            ),
            149 => 
            array (
                'created_at' => '2023-05-01 05:57:43',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 221,
                'name' => 'Measurement Permanent_delete',
                'parent' => 'Measurement',
                'status' => 1,
                'updated_at' => '2023-05-01 05:57:43',
            ),
            150 => 
            array (
                'created_at' => '2023-05-01 07:04:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 222,
                'name' => 'Manage Product List',
                'parent' => 'Manage Product',
                'status' => 1,
                'updated_at' => '2023-05-01 07:04:09',
            ),
            151 => 
            array (
                'created_at' => '2023-05-01 07:04:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 223,
                'name' => 'Manage Product Edit',
                'parent' => 'Manage Product',
                'status' => 1,
                'updated_at' => '2023-05-01 07:04:09',
            ),
            152 => 
            array (
                'created_at' => '2023-05-01 07:04:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 224,
                'name' => 'Manage Product Delete',
                'parent' => 'Manage Product',
                'status' => 1,
                'updated_at' => '2023-05-01 07:04:09',
            ),
            153 => 
            array (
                'created_at' => '2023-05-01 07:04:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 225,
                'name' => 'Manage Product View',
                'parent' => 'Manage Product',
                'status' => 1,
                'updated_at' => '2023-05-01 07:04:09',
            ),
            154 => 
            array (
                'created_at' => '2023-05-01 07:04:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 226,
                'name' => 'Manage Product Edit_history',
                'parent' => 'Manage Product',
                'status' => 1,
                'updated_at' => '2023-05-01 07:04:09',
            ),
            155 => 
            array (
                'created_at' => '2023-05-01 07:04:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 227,
                'name' => 'Manage Product Deleted_list',
                'parent' => 'Manage Product',
                'status' => 1,
                'updated_at' => '2023-05-01 07:04:09',
            ),
            156 => 
            array (
                'created_at' => '2023-05-01 07:04:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 228,
                'name' => 'Manage Product Restore',
                'parent' => 'Manage Product',
                'status' => 1,
                'updated_at' => '2023-05-01 07:04:09',
            ),
            157 => 
            array (
                'created_at' => '2023-05-01 07:04:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 229,
                'name' => 'Manage Product Permanent_delete',
                'parent' => 'Manage Product',
                'status' => 1,
                'updated_at' => '2023-05-01 07:04:09',
            ),
            158 => 
            array (
                'created_at' => '2023-05-01 10:04:02',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 230,
                'name' => 'Purchase List',
                'parent' => 'Purchase',
                'status' => 1,
                'updated_at' => '2023-05-01 10:04:02',
            ),
            159 => 
            array (
                'created_at' => '2023-05-01 10:04:02',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 231,
                'name' => 'Purchase Create',
                'parent' => 'Purchase',
                'status' => 1,
                'updated_at' => '2023-05-01 10:04:02',
            ),
            160 => 
            array (
                'created_at' => '2023-05-01 10:04:02',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 232,
                'name' => 'Purchase Edit',
                'parent' => 'Purchase',
                'status' => 1,
                'updated_at' => '2023-05-01 10:04:02',
            ),
            161 => 
            array (
                'created_at' => '2023-05-01 10:04:02',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 233,
                'name' => 'Purchase Delete',
                'parent' => 'Purchase',
                'status' => 1,
                'updated_at' => '2023-05-01 10:04:02',
            ),
            162 => 
            array (
                'created_at' => '2023-05-01 10:04:02',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 234,
                'name' => 'Purchase View',
                'parent' => 'Purchase',
                'status' => 1,
                'updated_at' => '2023-05-01 10:04:02',
            ),
            163 => 
            array (
                'created_at' => '2023-05-01 10:04:02',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 235,
                'name' => 'Purchase Print',
                'parent' => 'Purchase',
                'status' => 1,
                'updated_at' => '2023-05-01 10:04:02',
            ),
            164 => 
            array (
                'created_at' => '2023-05-01 10:04:02',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 236,
                'name' => 'Purchase Edit_history',
                'parent' => 'Purchase',
                'status' => 1,
                'updated_at' => '2023-05-01 10:04:02',
            ),
            165 => 
            array (
                'created_at' => '2023-05-01 10:04:02',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 237,
                'name' => 'Purchase Deleted_list',
                'parent' => 'Purchase',
                'status' => 1,
                'updated_at' => '2023-05-01 10:04:02',
            ),
            166 => 
            array (
                'created_at' => '2023-05-01 10:04:02',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 238,
                'name' => 'Purchase Restore',
                'parent' => 'Purchase',
                'status' => 1,
                'updated_at' => '2023-05-01 10:04:02',
            ),
            167 => 
            array (
                'created_at' => '2023-05-01 10:04:02',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 239,
                'name' => 'Purchase Permanent_delete',
                'parent' => 'Purchase',
                'status' => 1,
                'updated_at' => '2023-05-01 10:04:02',
            ),
            168 => 
            array (
                'created_at' => '2023-05-02 05:12:33',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 240,
                'name' => 'Measurement Sub Unit List',
                'parent' => 'Measurement Sub Unit',
                'status' => 1,
                'updated_at' => '2023-05-02 05:12:33',
            ),
            169 => 
            array (
                'created_at' => '2023-05-02 05:12:33',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 241,
                'name' => 'Measurement Sub Unit Create',
                'parent' => 'Measurement Sub Unit',
                'status' => 1,
                'updated_at' => '2023-05-02 05:12:33',
            ),
            170 => 
            array (
                'created_at' => '2023-05-02 05:12:34',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 242,
                'name' => 'Measurement Sub Unit Edit',
                'parent' => 'Measurement Sub Unit',
                'status' => 1,
                'updated_at' => '2023-05-02 05:12:34',
            ),
            171 => 
            array (
                'created_at' => '2023-05-02 05:12:34',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 243,
                'name' => 'Measurement Sub Unit Delete',
                'parent' => 'Measurement Sub Unit',
                'status' => 1,
                'updated_at' => '2023-05-02 05:12:34',
            ),
            172 => 
            array (
                'created_at' => '2023-05-02 05:12:34',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 244,
                'name' => 'Measurement Sub Unit View',
                'parent' => 'Measurement Sub Unit',
                'status' => 1,
                'updated_at' => '2023-05-02 05:12:34',
            ),
            173 => 
            array (
                'created_at' => '2023-05-02 05:12:34',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 245,
                'name' => 'Measurement Sub Unit Print',
                'parent' => 'Measurement Sub Unit',
                'status' => 1,
                'updated_at' => '2023-05-02 05:12:34',
            ),
            174 => 
            array (
                'created_at' => '2023-05-02 05:12:34',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 246,
                'name' => 'Measurement Sub Unit Edit_history',
                'parent' => 'Measurement Sub Unit',
                'status' => 1,
                'updated_at' => '2023-05-02 05:12:34',
            ),
            175 => 
            array (
                'created_at' => '2023-05-02 05:12:34',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 247,
                'name' => 'Measurement Sub Unit Deleted_list',
                'parent' => 'Measurement Sub Unit',
                'status' => 1,
                'updated_at' => '2023-05-02 05:12:34',
            ),
            176 => 
            array (
                'created_at' => '2023-05-02 05:12:34',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 248,
                'name' => 'Measurement Sub Unit Restore',
                'parent' => 'Measurement Sub Unit',
                'status' => 1,
                'updated_at' => '2023-05-02 05:12:34',
            ),
            177 => 
            array (
                'created_at' => '2023-05-02 05:12:34',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 249,
                'name' => 'Measurement Sub Unit Permanent_delete',
                'parent' => 'Measurement Sub Unit',
                'status' => 1,
                'updated_at' => '2023-05-02 05:12:34',
            ),
            178 => 
            array (
                'created_at' => '2023-05-02 10:53:17',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 250,
                'name' => 'Website Informaiton List',
                'parent' => 'Website Informaiton',
                'status' => 1,
                'updated_at' => '2023-05-02 10:53:17',
            ),
            179 => 
            array (
                'created_at' => '2023-05-02 10:53:17',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 251,
                'name' => 'Website Informaiton Create',
                'parent' => 'Website Informaiton',
                'status' => 1,
                'updated_at' => '2023-05-02 10:53:17',
            ),
            180 => 
            array (
                'created_at' => '2023-05-02 10:53:17',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 252,
                'name' => 'Website Informaiton Edit',
                'parent' => 'Website Informaiton',
                'status' => 1,
                'updated_at' => '2023-05-02 10:53:17',
            ),
            181 => 
            array (
                'created_at' => '2023-05-02 10:53:17',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 253,
                'name' => 'Website Informaiton Delete',
                'parent' => 'Website Informaiton',
                'status' => 1,
                'updated_at' => '2023-05-02 10:53:17',
            ),
            182 => 
            array (
                'created_at' => '2023-05-02 10:53:17',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 254,
                'name' => 'Website Informaiton View',
                'parent' => 'Website Informaiton',
                'status' => 1,
                'updated_at' => '2023-05-02 10:53:17',
            ),
            183 => 
            array (
                'created_at' => '2023-05-02 10:53:17',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 255,
                'name' => 'Website Informaiton Print',
                'parent' => 'Website Informaiton',
                'status' => 1,
                'updated_at' => '2023-05-02 10:53:17',
            ),
            184 => 
            array (
                'created_at' => '2023-05-02 10:53:17',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 256,
                'name' => 'Website Informaiton Edit_history',
                'parent' => 'Website Informaiton',
                'status' => 1,
                'updated_at' => '2023-05-02 10:53:17',
            ),
            185 => 
            array (
                'created_at' => '2023-05-02 10:53:17',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 257,
                'name' => 'Website Informaiton Deleted_list',
                'parent' => 'Website Informaiton',
                'status' => 1,
                'updated_at' => '2023-05-02 10:53:17',
            ),
            186 => 
            array (
                'created_at' => '2023-05-02 10:53:17',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 258,
                'name' => 'Website Informaiton Restore',
                'parent' => 'Website Informaiton',
                'status' => 1,
                'updated_at' => '2023-05-02 10:53:17',
            ),
            187 => 
            array (
                'created_at' => '2023-05-02 10:53:17',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 259,
                'name' => 'Website Informaiton Permanent_delete',
                'parent' => 'Website Informaiton',
                'status' => 1,
                'updated_at' => '2023-05-02 10:53:17',
            ),
            188 => 
            array (
                'created_at' => '2023-05-03 06:24:30',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 260,
                'name' => 'Product Stock List',
                'parent' => 'Product Stock',
                'status' => 1,
                'updated_at' => '2023-05-03 06:24:30',
            ),
            189 => 
            array (
                'created_at' => '2023-05-03 06:24:30',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 261,
                'name' => 'Product Stock Create',
                'parent' => 'Product Stock',
                'status' => 1,
                'updated_at' => '2023-05-03 06:24:30',
            ),
            190 => 
            array (
                'created_at' => '2023-05-03 06:24:30',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 262,
                'name' => 'Product Stock Edit',
                'parent' => 'Product Stock',
                'status' => 1,
                'updated_at' => '2023-05-03 06:24:30',
            ),
            191 => 
            array (
                'created_at' => '2023-05-03 06:24:30',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 263,
                'name' => 'Product Stock Delete',
                'parent' => 'Product Stock',
                'status' => 1,
                'updated_at' => '2023-05-03 06:24:30',
            ),
            192 => 
            array (
                'created_at' => '2023-05-03 06:24:30',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 264,
                'name' => 'Product Stock View',
                'parent' => 'Product Stock',
                'status' => 1,
                'updated_at' => '2023-05-03 06:24:30',
            ),
            193 => 
            array (
                'created_at' => '2023-05-03 06:24:30',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 265,
                'name' => 'Product Stock Print',
                'parent' => 'Product Stock',
                'status' => 1,
                'updated_at' => '2023-05-03 06:24:30',
            ),
            194 => 
            array (
                'created_at' => '2023-05-03 06:24:30',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 266,
                'name' => 'Product Stock Edit_history',
                'parent' => 'Product Stock',
                'status' => 1,
                'updated_at' => '2023-05-03 06:24:30',
            ),
            195 => 
            array (
                'created_at' => '2023-05-03 06:24:30',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 267,
                'name' => 'Product Stock Deleted_list',
                'parent' => 'Product Stock',
                'status' => 1,
                'updated_at' => '2023-05-03 06:24:30',
            ),
            196 => 
            array (
                'created_at' => '2023-05-03 06:24:30',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 268,
                'name' => 'Product Stock Restore',
                'parent' => 'Product Stock',
                'status' => 1,
                'updated_at' => '2023-05-03 06:24:30',
            ),
            197 => 
            array (
                'created_at' => '2023-05-03 06:24:30',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 269,
                'name' => 'Product Stock Permanent_delete',
                'parent' => 'Product Stock',
                'status' => 1,
                'updated_at' => '2023-05-03 06:24:30',
            ),
            198 => 
            array (
                'created_at' => '2023-05-03 07:07:38',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 270,
                'name' => 'Sales List',
                'parent' => 'Sales',
                'status' => 1,
                'updated_at' => '2023-05-03 07:07:38',
            ),
            199 => 
            array (
                'created_at' => '2023-05-03 07:07:38',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 271,
                'name' => 'Sales Create',
                'parent' => 'Sales',
                'status' => 1,
                'updated_at' => '2023-05-03 07:07:38',
            ),
            200 => 
            array (
                'created_at' => '2023-05-03 07:07:38',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 272,
                'name' => 'Sales Edit',
                'parent' => 'Sales',
                'status' => 1,
                'updated_at' => '2023-05-03 07:07:38',
            ),
            201 => 
            array (
                'created_at' => '2023-05-03 07:07:38',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 273,
                'name' => 'Sales Delete',
                'parent' => 'Sales',
                'status' => 1,
                'updated_at' => '2023-05-03 07:07:38',
            ),
            202 => 
            array (
                'created_at' => '2023-05-03 07:07:38',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 274,
                'name' => 'Sales View',
                'parent' => 'Sales',
                'status' => 1,
                'updated_at' => '2023-05-03 07:07:38',
            ),
            203 => 
            array (
                'created_at' => '2023-05-03 07:07:38',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 275,
                'name' => 'Sales Print',
                'parent' => 'Sales',
                'status' => 1,
                'updated_at' => '2023-05-03 07:07:38',
            ),
            204 => 
            array (
                'created_at' => '2023-05-03 07:07:38',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 276,
                'name' => 'Sales Edit_history',
                'parent' => 'Sales',
                'status' => 1,
                'updated_at' => '2023-05-03 07:07:38',
            ),
            205 => 
            array (
                'created_at' => '2023-05-03 07:07:38',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 277,
                'name' => 'Sales Deleted_list',
                'parent' => 'Sales',
                'status' => 1,
                'updated_at' => '2023-05-03 07:07:38',
            ),
            206 => 
            array (
                'created_at' => '2023-05-03 07:07:38',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 278,
                'name' => 'Sales Restore',
                'parent' => 'Sales',
                'status' => 1,
                'updated_at' => '2023-05-03 07:07:38',
            ),
            207 => 
            array (
                'created_at' => '2023-05-03 07:07:38',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 279,
                'name' => 'Sales Permanent_delete',
                'parent' => 'Sales',
                'status' => 1,
                'updated_at' => '2023-05-03 07:07:38',
            ),
        ));
        
        
    }
}