<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UserMenuActionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('user_menu_actions')->delete();
        
        \DB::table('user_menu_actions')->insert(array (
            0 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-03-19 18:08:09',
                'deleted_at' => NULL,
                'id' => 1,
                'is_hidden' => 'No',
                'menu_action_id' => 1,
                'menu_id' => 3,
                'name' => 'Create',
                'new_tab' => 0,
                'order_by' => 1,
                'parent_id' => NULL,
                'route_name' => 'user.create',
                'show_in_table' => 0,
                'slug' => NULL,
                'status' => 1,
                'system_name' => 'Create',
                'type' => 'action',
                'updated_at' => '2023-04-05 06:48:45',
            ),
            1 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-03-19 18:08:09',
                'deleted_at' => NULL,
                'id' => 2,
                'is_hidden' => 'No',
                'menu_action_id' => 2,
                'menu_id' => 3,
                'name' => 'Edit',
                'new_tab' => 0,
                'order_by' => 2,
                'parent_id' => NULL,
                'route_name' => 'user.edit',
                'show_in_table' => 1,
                'slug' => NULL,
                'status' => 1,
                'system_name' => 'Edit',
                'type' => 'action',
                'updated_at' => '2023-04-05 06:48:45',
            ),
            2 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-03-19 18:08:09',
                'deleted_at' => NULL,
                'id' => 3,
                'is_hidden' => 'No',
                'menu_action_id' => 3,
                'menu_id' => 3,
                'name' => 'Delete',
                'new_tab' => 0,
                'order_by' => 4,
                'parent_id' => NULL,
                'route_name' => 'user.destroy',
                'show_in_table' => 1,
                'slug' => NULL,
                'status' => 1,
                'system_name' => 'Delete',
                'type' => 'action',
                'updated_at' => '2023-04-05 06:48:45',
            ),
            3 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-03-19 18:08:09',
                'deleted_at' => NULL,
                'id' => 4,
                'is_hidden' => 'No',
                'menu_action_id' => 4,
                'menu_id' => 3,
                'name' => 'View',
                'new_tab' => 0,
                'order_by' => 3,
                'parent_id' => NULL,
                'route_name' => 'user.show',
                'show_in_table' => 1,
                'slug' => NULL,
                'status' => 0,
                'system_name' => 'View',
                'type' => 'action',
                'updated_at' => '2023-04-05 06:48:45',
            ),
            4 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-03-19 18:08:09',
                'deleted_at' => NULL,
                'id' => 5,
                'is_hidden' => 'No',
                'menu_action_id' => 8,
                'menu_id' => 3,
                'name' => 'Print',
                'new_tab' => 1,
                'order_by' => 5,
                'parent_id' => NULL,
                'route_name' => 'user.print',
                'show_in_table' => 1,
                'slug' => NULL,
                'status' => 0,
                'system_name' => 'Print',
                'type' => 'action',
                'updated_at' => '2023-04-05 06:48:45',
            ),
            5 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'id' => 6,
                'is_hidden' => 'No',
                'menu_action_id' => NULL,
                'menu_id' => 3,
                'name' => 'Deleted Index',
                'new_tab' => 0,
                'order_by' => 7,
                'parent_id' => NULL,
                'route_name' => 'user.deleted_list',
                'show_in_table' => 0,
                'slug' => 'deleted_list',
                'status' => 1,
                'system_name' => 'Deleted Index',
                'type' => 'action',
                'updated_at' => '2023-04-05 06:48:45',
            ),
            6 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-03-19 18:08:09',
                'deleted_at' => NULL,
                'id' => 7,
                'is_hidden' => 'No',
                'menu_action_id' => 9,
                'menu_id' => 3,
                'name' => 'Restore',
                'new_tab' => 0,
                'order_by' => 7,
                'parent_id' => 6,
                'route_name' => 'user.restore',
                'show_in_table' => 1,
                'slug' => 'restore',
                'status' => 1,
                'system_name' => 'Restore',
                'type' => 'action',
                'updated_at' => '2023-04-05 06:48:45',
            ),
            7 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'id' => 8,
                'is_hidden' => 'No',
                'menu_action_id' => 1,
                'menu_id' => 5,
                'name' => 'Create',
                'new_tab' => 0,
                'order_by' => 1,
                'parent_id' => NULL,
                'route_name' => 'role.create',
                'show_in_table' => 0,
                'slug' => NULL,
                'status' => 1,
                'system_name' => 'Create',
                'type' => 'action',
                'updated_at' => '2023-04-05 06:48:45',
            ),
            8 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'id' => 9,
                'is_hidden' => 'No',
                'menu_action_id' => 2,
                'menu_id' => 5,
                'name' => 'Edit',
                'new_tab' => 0,
                'order_by' => 2,
                'parent_id' => NULL,
                'route_name' => 'role.edit',
                'show_in_table' => 1,
                'slug' => NULL,
                'status' => 1,
                'system_name' => 'Edit',
                'type' => 'action',
                'updated_at' => '2023-04-05 06:48:45',
            ),
            9 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'id' => 10,
                'is_hidden' => 'No',
                'menu_action_id' => 3,
                'menu_id' => 5,
                'name' => 'Delete',
                'new_tab' => 0,
                'order_by' => 4,
                'parent_id' => NULL,
                'route_name' => 'role.destroy',
                'show_in_table' => 1,
                'slug' => NULL,
                'status' => 1,
                'system_name' => 'Delete',
                'type' => 'action',
                'updated_at' => '2023-04-05 06:48:45',
            ),
            10 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'id' => 11,
                'is_hidden' => 'No',
                'menu_action_id' => 4,
                'menu_id' => 5,
                'name' => 'View',
                'new_tab' => 0,
                'order_by' => 3,
                'parent_id' => NULL,
                'route_name' => 'role.show',
                'show_in_table' => 1,
                'slug' => NULL,
                'status' => 0,
                'system_name' => 'View',
                'type' => 'action',
                'updated_at' => '2023-04-05 06:48:45',
            ),
            11 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'id' => 12,
                'is_hidden' => 'No',
                'menu_action_id' => 8,
                'menu_id' => 5,
                'name' => 'Print',
                'new_tab' => 1,
                'order_by' => 5,
                'parent_id' => NULL,
                'route_name' => 'role.print',
                'show_in_table' => 1,
                'slug' => NULL,
                'status' => 0,
                'system_name' => 'Print',
                'type' => 'action',
                'updated_at' => '2023-04-05 06:48:45',
            ),
            12 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'id' => 13,
                'is_hidden' => 'No',
                'menu_action_id' => NULL,
                'menu_id' => 5,
                'name' => 'Deleted Index',
                'new_tab' => 0,
                'order_by' => 7,
                'parent_id' => NULL,
                'route_name' => 'role.deleted_list',
                'show_in_table' => 0,
                'slug' => 'deleted_list',
                'status' => 1,
                'system_name' => 'Deleted Index',
                'type' => 'action',
                'updated_at' => '2023-04-05 06:48:45',
            ),
            13 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'id' => 14,
                'is_hidden' => 'No',
                'menu_action_id' => 9,
                'menu_id' => 5,
                'name' => 'Restore',
                'new_tab' => 0,
                'order_by' => 7,
                'parent_id' => 13,
                'route_name' => 'role.restore',
                'show_in_table' => 1,
                'slug' => 'restore',
                'status' => 1,
                'system_name' => 'Restore',
                'type' => 'action',
                'updated_at' => '2023-04-05 06:48:45',
            ),
            14 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'id' => 15,
                'is_hidden' => 'No',
                'menu_action_id' => 5,
                'menu_id' => 5,
                'name' => 'Permission',
                'new_tab' => 0,
                'order_by' => 7,
                'parent_id' => NULL,
                'route_name' => 'role.permission',
                'show_in_table' => 1,
                'slug' => 'permission',
                'status' => 1,
                'system_name' => 'Permission',
                'type' => 'action',
                'updated_at' => '2023-04-05 06:48:45',
            ),
            15 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'id' => 171,
                'is_hidden' => 'No',
                'menu_action_id' => 1,
                'menu_id' => 26,
                'name' => 'Create',
                'new_tab' => 0,
                'order_by' => 1,
                'parent_id' => NULL,
                'route_name' => 'menu.create',
                'show_in_table' => 0,
                'slug' => NULL,
                'status' => 1,
                'system_name' => 'Create',
                'type' => 'action',
                'updated_at' => '2023-04-05 06:48:48',
            ),
            16 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'id' => 172,
                'is_hidden' => 'No',
                'menu_action_id' => 2,
                'menu_id' => 26,
                'name' => 'Edit',
                'new_tab' => 0,
                'order_by' => 2,
                'parent_id' => NULL,
                'route_name' => 'menu.edit',
                'show_in_table' => 1,
                'slug' => NULL,
                'status' => 1,
                'system_name' => 'Edit',
                'type' => 'action',
                'updated_at' => '2023-04-05 06:48:48',
            ),
            17 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'id' => 173,
                'is_hidden' => 'No',
                'menu_action_id' => 3,
                'menu_id' => 26,
                'name' => 'Delete',
                'new_tab' => 0,
                'order_by' => 4,
                'parent_id' => NULL,
                'route_name' => 'menu.destroy',
                'show_in_table' => 1,
                'slug' => NULL,
                'status' => 1,
                'system_name' => 'Delete',
                'type' => 'action',
                'updated_at' => '2023-04-05 06:48:48',
            ),
            18 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'id' => 174,
                'is_hidden' => 'No',
                'menu_action_id' => 4,
                'menu_id' => 26,
                'name' => 'View',
                'new_tab' => 0,
                'order_by' => 3,
                'parent_id' => NULL,
                'route_name' => 'menu.show',
                'show_in_table' => 1,
                'slug' => NULL,
                'status' => 1,
                'system_name' => 'View',
                'type' => 'action',
                'updated_at' => '2023-04-05 06:48:48',
            ),
            19 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'id' => 175,
                'is_hidden' => 'No',
                'menu_action_id' => NULL,
                'menu_id' => 26,
                'name' => 'Trash',
                'new_tab' => 0,
                'order_by' => 6,
                'parent_id' => NULL,
                'route_name' => 'menu.deleted_list',
                'show_in_table' => 0,
                'slug' => 'deleted_list',
                'status' => 1,
                'system_name' => 'Trash',
                'type' => 'tab',
                'updated_at' => '2023-04-05 06:48:48',
            ),
            20 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'id' => 176,
                'is_hidden' => 'No',
                'menu_action_id' => 9,
                'menu_id' => 26,
                'name' => 'Restore',
                'new_tab' => 0,
                'order_by' => 7,
                'parent_id' => 175,
                'route_name' => 'menu.restore',
                'show_in_table' => 1,
                'slug' => 'restore',
                'status' => 1,
                'system_name' => 'Restore',
                'type' => 'action',
                'updated_at' => '2023-04-05 06:48:48',
            ),
            21 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'id' => 177,
                'is_hidden' => 'No',
                'menu_action_id' => 3,
                'menu_id' => 26,
                'name' => 'Delete Permanently',
                'new_tab' => 0,
                'order_by' => 8,
                'parent_id' => 175,
                'route_name' => 'menu.force_destroy',
                'show_in_table' => 1,
                'slug' => 'force_destroy',
                'status' => 1,
                'system_name' => 'Delete Permanently',
                'type' => 'action',
                'updated_at' => '2023-04-05 06:48:48',
            ),
            22 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-19 07:39:32',
                'deleted_at' => NULL,
                'id' => 205,
                'is_hidden' => 'No',
                'menu_action_id' => 1,
                'menu_id' => 33,
                'name' => 'Create',
                'new_tab' => 0,
                'order_by' => 1,
                'parent_id' => NULL,
                'route_name' => 'company.create',
                'show_in_table' => 0,
                'slug' => NULL,
                'status' => 1,
                'system_name' => 'Create',
                'type' => 'action',
                'updated_at' => '2023-04-19 07:39:32',
            ),
            23 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-19 07:39:32',
                'deleted_at' => NULL,
                'id' => 206,
                'is_hidden' => 'No',
                'menu_action_id' => 2,
                'menu_id' => 33,
                'name' => 'Edit',
                'new_tab' => 0,
                'order_by' => 2,
                'parent_id' => NULL,
                'route_name' => 'company.edit',
                'show_in_table' => 1,
                'slug' => NULL,
                'status' => 1,
                'system_name' => 'Edit',
                'type' => 'action',
                'updated_at' => '2023-04-19 07:39:32',
            ),
            24 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-19 07:39:32',
                'deleted_at' => NULL,
                'id' => 207,
                'is_hidden' => 'No',
                'menu_action_id' => 3,
                'menu_id' => 33,
                'name' => 'Delete',
                'new_tab' => 0,
                'order_by' => 4,
                'parent_id' => NULL,
                'route_name' => 'company.destroy',
                'show_in_table' => 1,
                'slug' => NULL,
                'status' => 1,
                'system_name' => 'Delete',
                'type' => 'action',
                'updated_at' => '2023-04-19 07:39:32',
            ),
            25 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-19 07:39:32',
                'deleted_at' => NULL,
                'id' => 208,
                'is_hidden' => 'No',
                'menu_action_id' => 4,
                'menu_id' => 33,
                'name' => 'View',
                'new_tab' => 0,
                'order_by' => 3,
                'parent_id' => NULL,
                'route_name' => 'company.show',
                'show_in_table' => 1,
                'slug' => NULL,
                'status' => 1,
                'system_name' => 'View',
                'type' => 'action',
                'updated_at' => '2023-04-19 07:39:32',
            ),
            26 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-19 07:39:32',
                'deleted_at' => NULL,
                'id' => 209,
                'is_hidden' => 'No',
                'menu_action_id' => 8,
                'menu_id' => 33,
                'name' => 'Print',
                'new_tab' => 1,
                'order_by' => 5,
                'parent_id' => NULL,
                'route_name' => 'company.print',
                'show_in_table' => 1,
                'slug' => NULL,
                'status' => 1,
                'system_name' => 'Print',
                'type' => 'action',
                'updated_at' => '2023-04-19 07:39:32',
            ),
            27 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-19 07:39:32',
                'deleted_at' => NULL,
                'id' => 210,
                'is_hidden' => 'No',
                'menu_action_id' => 10,
                'menu_id' => 33,
                'name' => 'Edit History',
                'new_tab' => 0,
                'order_by' => 9,
                'parent_id' => NULL,
                'route_name' => 'company.edit_history',
                'show_in_table' => 1,
                'slug' => 'edit_history',
                'status' => 1,
                'system_name' => 'Edit History',
                'type' => 'action',
                'updated_at' => '2023-04-19 07:39:32',
            ),
            28 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-19 07:39:32',
                'deleted_at' => NULL,
                'id' => 211,
                'is_hidden' => 'No',
                'menu_action_id' => NULL,
                'menu_id' => 33,
                'name' => 'Trash',
                'new_tab' => 0,
                'order_by' => 6,
                'parent_id' => NULL,
                'route_name' => 'company.deleted_list',
                'show_in_table' => 0,
                'slug' => 'deleted_list',
                'status' => 1,
                'system_name' => 'Trash',
                'type' => 'tab',
                'updated_at' => '2023-04-19 07:39:32',
            ),
            29 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-19 07:39:32',
                'deleted_at' => NULL,
                'id' => 212,
                'is_hidden' => 'No',
                'menu_action_id' => 9,
                'menu_id' => 33,
                'name' => 'Restore',
                'new_tab' => 0,
                'order_by' => 7,
                'parent_id' => 211,
                'route_name' => 'company.restore',
                'show_in_table' => 1,
                'slug' => 'restore',
                'status' => 1,
                'system_name' => 'Restore',
                'type' => 'action',
                'updated_at' => '2023-04-19 07:39:32',
            ),
            30 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-19 07:39:32',
                'deleted_at' => NULL,
                'id' => 213,
                'is_hidden' => 'No',
                'menu_action_id' => 3,
                'menu_id' => 33,
                'name' => 'Delete Permanently',
                'new_tab' => 0,
                'order_by' => 8,
                'parent_id' => 211,
                'route_name' => 'company.force_destroy',
                'show_in_table' => 1,
                'slug' => 'force_destroy',
                'status' => 1,
                'system_name' => 'Delete Permanently',
                'type' => 'action',
                'updated_at' => '2023-04-19 07:39:32',
            ),
            31 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-19 07:41:20',
                'deleted_at' => NULL,
                'id' => 214,
                'is_hidden' => 'No',
                'menu_action_id' => 1,
                'menu_id' => 35,
                'name' => 'Create',
                'new_tab' => 0,
                'order_by' => 1,
                'parent_id' => NULL,
                'route_name' => 'customer.create',
                'show_in_table' => 0,
                'slug' => NULL,
                'status' => 1,
                'system_name' => 'Create',
                'type' => 'action',
                'updated_at' => '2023-04-19 07:41:20',
            ),
            32 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-19 07:41:20',
                'deleted_at' => NULL,
                'id' => 215,
                'is_hidden' => 'No',
                'menu_action_id' => 2,
                'menu_id' => 35,
                'name' => 'Edit',
                'new_tab' => 0,
                'order_by' => 2,
                'parent_id' => NULL,
                'route_name' => 'customer.edit',
                'show_in_table' => 1,
                'slug' => NULL,
                'status' => 1,
                'system_name' => 'Edit',
                'type' => 'action',
                'updated_at' => '2023-04-19 07:41:20',
            ),
            33 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-19 07:41:20',
                'deleted_at' => NULL,
                'id' => 216,
                'is_hidden' => 'No',
                'menu_action_id' => 3,
                'menu_id' => 35,
                'name' => 'Delete',
                'new_tab' => 0,
                'order_by' => 4,
                'parent_id' => NULL,
                'route_name' => 'customer.destroy',
                'show_in_table' => 1,
                'slug' => NULL,
                'status' => 1,
                'system_name' => 'Delete',
                'type' => 'action',
                'updated_at' => '2023-04-19 07:41:20',
            ),
            34 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-19 07:41:20',
                'deleted_at' => NULL,
                'id' => 217,
                'is_hidden' => 'No',
                'menu_action_id' => 4,
                'menu_id' => 35,
                'name' => 'View',
                'new_tab' => 0,
                'order_by' => 3,
                'parent_id' => NULL,
                'route_name' => 'customer.show',
                'show_in_table' => 1,
                'slug' => NULL,
                'status' => 1,
                'system_name' => 'View',
                'type' => 'action',
                'updated_at' => '2023-04-19 07:41:20',
            ),
            35 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-19 07:41:20',
                'deleted_at' => NULL,
                'id' => 218,
                'is_hidden' => 'No',
                'menu_action_id' => 8,
                'menu_id' => 35,
                'name' => 'Print',
                'new_tab' => 1,
                'order_by' => 5,
                'parent_id' => NULL,
                'route_name' => 'customer.print',
                'show_in_table' => 1,
                'slug' => NULL,
                'status' => 1,
                'system_name' => 'Print',
                'type' => 'action',
                'updated_at' => '2023-04-19 07:41:20',
            ),
            36 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-19 07:41:20',
                'deleted_at' => NULL,
                'id' => 219,
                'is_hidden' => 'No',
                'menu_action_id' => 10,
                'menu_id' => 35,
                'name' => 'Edit History',
                'new_tab' => 0,
                'order_by' => 9,
                'parent_id' => NULL,
                'route_name' => 'customer.edit_history',
                'show_in_table' => 1,
                'slug' => 'edit_history',
                'status' => 1,
                'system_name' => 'Edit History',
                'type' => 'action',
                'updated_at' => '2023-04-19 07:41:20',
            ),
            37 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-19 07:41:20',
                'deleted_at' => NULL,
                'id' => 220,
                'is_hidden' => 'No',
                'menu_action_id' => NULL,
                'menu_id' => 35,
                'name' => 'Trash',
                'new_tab' => 0,
                'order_by' => 6,
                'parent_id' => NULL,
                'route_name' => 'customer.deleted_list',
                'show_in_table' => 0,
                'slug' => 'deleted_list',
                'status' => 1,
                'system_name' => 'Trash',
                'type' => 'tab',
                'updated_at' => '2023-04-19 07:41:20',
            ),
            38 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-19 07:41:20',
                'deleted_at' => NULL,
                'id' => 221,
                'is_hidden' => 'No',
                'menu_action_id' => 9,
                'menu_id' => 35,
                'name' => 'Restore',
                'new_tab' => 0,
                'order_by' => 7,
                'parent_id' => 220,
                'route_name' => 'customer.restore',
                'show_in_table' => 1,
                'slug' => 'restore',
                'status' => 1,
                'system_name' => 'Restore',
                'type' => 'action',
                'updated_at' => '2023-04-19 07:41:20',
            ),
            39 => 
            array (
                'bn_name' => NULL,
                'class' => NULL,
                'created_at' => '2023-04-19 07:41:20',
                'deleted_at' => NULL,
                'id' => 222,
                'is_hidden' => 'No',
                'menu_action_id' => 3,
                'menu_id' => 35,
                'name' => 'Delete Permanently',
                'new_tab' => 0,
                'order_by' => 8,
                'parent_id' => 220,
                'route_name' => 'customer.force_destroy',
                'show_in_table' => 1,
                'slug' => 'force_destroy',
                'status' => 1,
                'system_name' => 'Delete Permanently',
                'type' => 'action',
                'updated_at' => '2023-04-19 07:41:20',
            ),
        ));
        
        
    }
}